// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAnswersByQuestion = `-- name: GetAnswersByQuestion :many
SELECT id, session_id, student_id, question_id, selected_option, answered_at FROM answers
WHERE session_id = $1 AND question_id = $2
`

type GetAnswersByQuestionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetAnswersByQuestion(ctx context.Context, arg GetAnswersByQuestionParams) ([]Answer, error) {
	rows, err := q.db.Query(ctx, getAnswersByQuestion, arg.SessionID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.QuestionID,
			&i.SelectedOption,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitAnswer = `-- name: SubmitAnswer :one
INSERT INTO answers (
    session_id,
    student_id,
    question_id,
    selected_option
) VALUES ($1, $2, $3, $4)
ON CONFLICT (student_id, question_id)
DO UPDATE SET
    selected_option = EXCLUDED.selected_option,
    answered_at = now()
RETURNING id, session_id, student_id, question_id, selected_option, answered_at
`

type SubmitAnswerParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	StudentID      uuid.UUID `json:"student_id"`
	QuestionID     uuid.UUID `json:"question_id"`
	SelectedOption int32     `json:"selected_option"`
}

func (q *Queries) SubmitAnswer(ctx context.Context, arg SubmitAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, submitAnswer,
		arg.SessionID,
		arg.StudentID,
		arg.QuestionID,
		arg.SelectedOption,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.QuestionID,
		&i.SelectedOption,
		&i.AnsweredAt,
	)
	return i, err
}
