// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	StudentID      uuid.UUID `json:"student_id"`
	QuestionID     uuid.UUID `json:"question_id"`
	SelectedOption int32     `json:"selected_option"`
	AnsweredAt     time.Time `json:"answered_at"`
}

type Question struct {
	ID               uuid.UUID `json:"id"`
	QuizID           uuid.UUID `json:"quiz_id"`
	Text             string    `json:"text"`
	Options          []byte    `json:"options"`
	CorrectOption    int32     `json:"correct_option"`
	TimeLimitSeconds int32     `json:"time_limit_seconds"`
	OrderIndex       int32     `json:"order_index"`
	CreatedAt        time.Time `json:"created_at"`
}

type Quiz struct {
	ID        uuid.UUID `json:"id"`
	TeacherID uuid.UUID `json:"teacher_id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID                   uuid.UUID          `json:"id"`
	QuizID               uuid.UUID          `json:"quiz_id"`
	JoinCode             string             `json:"join_code"`
	Status               string             `json:"status"`
	CurrentQuestionIndex int32              `json:"current_question_index"`
	QuestionStartedAt    pgtype.Timestamptz `json:"question_started_at"`
	CreatedAt            time.Time          `json:"created_at"`
}

type Student struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	Name      string    `json:"name"`
	JoinedAt  time.Time `json:"joined_at"`
}

type Teacher struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
