// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceQuestion(ctx context.Context, id uuid.UUID) (Session, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	EndSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetAnswersByQuestion(ctx context.Context, arg GetAnswersByQuestionParams) ([]Answer, error)
	GetQuestionsByQuiz(ctx context.Context, quizID uuid.UUID) ([]Question, error)
	GetQuizByID(ctx context.Context, id uuid.UUID) (Quiz, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByJoinCode(ctx context.Context, joinCode string) (Session, error)
	GetStudentsBySession(ctx context.Context, sessionID uuid.UUID) ([]Student, error)
	GetTeacherByEmail(ctx context.Context, email string) (Teacher, error)
	StartSession(ctx context.Context, id uuid.UUID) (Session, error)
	SubmitAnswer(ctx context.Context, arg SubmitAnswerParams) (Answer, error)
}

var _ Querier = (*Queries)(nil)
