// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    quiz_id,
    text,
    options,
    correct_option,
    time_limit_seconds,
    order_index
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, quiz_id, text, options, correct_option, time_limit_seconds, order_index, created_at
`

type CreateQuestionParams struct {
	QuizID           uuid.UUID `json:"quiz_id"`
	Text             string    `json:"text"`
	Options          []byte    `json:"options"`
	CorrectOption    int32     `json:"correct_option"`
	TimeLimitSeconds int32     `json:"time_limit_seconds"`
	OrderIndex       int32     `json:"order_index"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.QuizID,
		arg.Text,
		arg.Options,
		arg.CorrectOption,
		arg.TimeLimitSeconds,
		arg.OrderIndex,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Options,
		&i.CorrectOption,
		&i.TimeLimitSeconds,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (teacher_id, title)
VALUES ($1, $2)
RETURNING id, teacher_id, title, created_at
`

type CreateQuizParams struct {
	TeacherID uuid.UUID `json:"teacher_id"`
	Title     string    `json:"title"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz, arg.TeacherID, arg.Title)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionsByQuiz = `-- name: GetQuestionsByQuiz :many
SELECT id, quiz_id, text, options, correct_option, time_limit_seconds, order_index, created_at FROM questions
WHERE quiz_id = $1
ORDER BY order_index ASC
`

func (q *Queries) GetQuestionsByQuiz(ctx context.Context, quizID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.Options,
			&i.CorrectOption,
			&i.TimeLimitSeconds,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizByID = `-- name: GetQuizByID :one
SELECT id, teacher_id, title, created_at FROM quizzes
WHERE id = $1
`

func (q *Queries) GetQuizByID(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByID, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}
