// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const advanceQuestion = `-- name: AdvanceQuestion :one
UPDATE sessions
SET current_question_index = current_question_index + 1,
    question_started_at = now()
WHERE id = $1
RETURNING id, quiz_id, join_code, status, current_question_index, question_started_at, created_at
`

func (q *Queries) AdvanceQuestion(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, advanceQuestion, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (quiz_id, join_code, status)
VALUES ($1, $2, 'WAITING')
RETURNING id, quiz_id, join_code, status, current_question_index, question_started_at, created_at
`

type CreateSessionParams struct {
	QuizID   uuid.UUID `json:"quiz_id"`
	JoinCode string    `json:"join_code"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.QuizID, arg.JoinCode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE sessions
SET status = 'ENDED'
WHERE id = $1
RETURNING id, quiz_id, join_code, status, current_question_index, question_started_at, created_at
`

func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, quiz_id, join_code, status, current_question_index, question_started_at, created_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByJoinCode = `-- name: GetSessionByJoinCode :one
SELECT id, quiz_id, join_code, status, current_question_index, question_started_at, created_at FROM sessions
WHERE join_code = $1
`

func (q *Queries) GetSessionByJoinCode(ctx context.Context, joinCode string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByJoinCode, joinCode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
UPDATE sessions
SET status = 'ACTIVE',
    current_question_index = 0,
    question_started_at = now()
WHERE id = $1
RETURNING id, quiz_id, join_code, status, current_question_index, question_started_at, created_at
`

func (q *Queries) StartSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, startSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.JoinCode,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.QuestionStartedAt,
		&i.CreatedAt,
	)
	return i, err
}
