// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (session_id, name)
VALUES ($1, $2)
RETURNING id, session_id, name, joined_at
`

type CreateStudentParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.SessionID, arg.Name)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Name,
		&i.JoinedAt,
	)
	return i, err
}

const getStudentsBySession = `-- name: GetStudentsBySession :many
SELECT id, session_id, name, joined_at FROM students
WHERE session_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) GetStudentsBySession(ctx context.Context, sessionID uuid.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Name,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
